In [120]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [121]:
import pandas as pd
import numpy as np
import json

In [122]:
#--------------------------------------------------------------------------------------------------------------------------
#
#--------------------------------------------------------------------------------------------------------------------------

In [123]:
from context import community_module, dao, communityModel
from communityModel.communityModel_notebook import CommunityModel
from dao.dao_json import DAO_json

In [124]:
filename = 'gam author agglomerative'
filename = 'gam iconclass agglomerative'
filename = 'gam iconclass emotion'
filename = 'GAM similar user sentiment in similar artworks (iconclass)'
filename = 'GAM similar user sentiment in similar artworks (iconclass) annotated-stories'
filename = "GAM similar user emotions in similar artworks (iconclass) annotated-stories"

In [125]:
# Perspective file (only the last one is used)


In [126]:
# Sentiments
filename = "GAM similar user sentiments in similar artworks (iconclass)"
filename = "GAM similar user sentiments in similar artworks (artist_country)"
filename = "GAM similar user sentiments in similar artworks (Materials)"



In [127]:
# Do the same as before with emotions
# Example: filename = "GAM similar user emotions in similar artworks (iconclass)"
filename = "GAM similar user emotions in similar artworks (iconclass)"



In [128]:
# Same with Plutchik Emotions
# Do the same as before with emotions
# Example: filename = "GAM similar user emotions in similar artworks (iconclass)"
filename = "GAM similar user plutchik emotions in similar artworks (iconclass)"



In [129]:
# Perspective (user attributes, artworks similarity features, emotion similarity on plutchik emotions similar artworks)
print('perspectives/GAM LDH/' + filename + '.json')
with open('perspectives/GAM LDH/' + filename + '.json', 'r', encoding='utf8') as f:
#with open('perspectives/GAM inSpice/' + filename + '.json', 'r', encoding='utf8') as f:
    perspective = json.load(f)
perspective

perspectives/GAM LDH/GAM similar user plutchik emotions in similar artworks (iconclass).json


{'id': 'GAM similar user plutchik emotions in similar artworks (iconclass)',
 'name': 'GAM similar user plutchik emotions in similar artworks (iconclass)',
 'algorithm': {'name': 'agglomerative', 'params': []},
 'similarity_functions': [{'sim_function': {'name': 'IconClassSimilarityDAO',
    'params': [],
    'on_attribute': {'att_name': 'Iconclass_subjects_curators',
     'att_type': 'String'},
    'weight': 0.8}}],
 'user_attributes': [{'att_name': 'relationship_with_arts',
   'att_type': 'String'},
  {'att_name': 'relationship_with_museums', 'att_type': 'String'}],
 'interaction_similarity_functions': [{'sim_function': {'name': 'PlutchikEmotionSimilarityDAO',
    'params': [],
    'on_attribute': {'att_name': 'plutchik_emotions', 'att_type': 'dict'},
    'interaction_object': {'att_name': 'IdArtefact', 'att_type': 'String'}}}]}

In [130]:
filename = 'data/generated/annotated_stories_merged.json'
filename = 'data/generated/GAM user_interactions merged.json'
filename = 'data/generated/GAM user_interactions mergedArtworks.json'



In [131]:
daoJson = DAO_json(filename)
df = daoJson.getPandasDataframe()
df

_id   userName           TimeStamps                     Gender_x  \
0        NaN   0bAAwK14                  NaT                          NaN   
1        NaN   6rK3p7za                  NaT                          NaN   
2   B3N0HGw4   B3N0HGw4  2022-01-10 17:07:46                      Femmina   
3        NaN   BTKF72et                  NaT                          NaN   
4   JgevtrSb   JgevtrSb  2022-09-30 11:16:16  Preferisco non specificarlo   
5   KQTGApjD   KQTGApjD  2022-01-10 16:59:07                      Femmina   
6   LW3Klzvx   LW3Klzvx  2022-01-10 17:09:19                      Femmina   
7   LvIeXwcT   LvIeXwcT  2022-01-10 10:53:03  Preferisco non specificarlo   
8   N72IRgFy   N72IRgFy  2022-01-10 16:23:52                      Maschio   
9   RQ4a2nIG   RQ4a2nIG  2022-01-10 11:21:12  Preferisco non specificarlo   
10  Sz5Wx2XD   Sz5Wx2XD  2022-01-10 17:47:27                      Maschio   
11  WYCImqGm   WYCImqGm  2022-01-10 15:54:48                      Femmina   
12  WsK2A1ab   WsK2A1ab  2022-01-10 14:56:53                      Maschio   
13  Y0WXF1LR   Y0WXF1LR  2022-01-10 17:21:17                      Femmina   
14  ZWrgWx9o   ZWrgWx9o  2022-01-10 14:06:45                      Maschio   
15       NaN  anonymous                  NaT                          NaN   
16  cBjFhvjx   cBjFhvjx  2022-01-10 16:58:18                      Maschio   
17       NaN   e4aM9WL7                  NaT                          NaN   
18       NaN   fqybaAk8                  NaT                          NaN   
19  loEoYm9R   loEoYm9R  2022-01-10 15:54:48                      Femmina   
20       NaN   ox8G7avH                  NaT                          NaN   
21  q2BDj1os   q2BDj1os  2022-01-10 15:15:45                      Maschio   
22  x2AUnHqw   x2AUnHqw  2022-01-10 15:45:38                      Femmina   
23  yjlouq5U   yjlouq5U  2022-01-10 17:20:01                      Femmina   

                            Age                 relationship_with_arts  \
0                           NaN                                    NaN   
1                           NaN                                    NaN   
2                    20-30 anni       Ho un forte interesse per l'arte   
3                           NaN                                    NaN   
4                         45-60       Ho un forte interesse per l'arte   
5                    20-30 anni               L'arte mi interessa poco   
6                    20-30 anni               L'arte mi interessa poco   
7                         45-60  Non provo nessun interesse per l'arte   
8                    13-19 anni               L'arte mi interessa poco   
9   Preferisco non specificarlo  Non provo nessun interesse per l'arte   
10                   20-30 anni       Ho un forte interesse per l'arte   
11                   20-30 anni       Ho un forte interesse per l'arte   
12                    più di 60               L'arte mi interessa poco   
13                    più di 60          Il mio lavoro riguarda l'arte   
14                   20-30 anni       Ho un forte interesse per l'arte   
15                          NaN                                    NaN   
16                   20-30 anni       Ho un forte interesse per l'arte   
17                          NaN                                    NaN   
18                          NaN                                    NaN   
19                   20-30 anni               L'arte mi interessa poco   
20                          NaN                                    NaN   
21                        45-60       Ho un forte interesse per l'arte   
22                   20-30 anni               L'arte mi interessa poco   
23                   20-30 anni       Ho un forte interesse per l'arte   

                  relationship_with_museums  \
0                                       NaN   
1                                       NaN   
2   Visito di tanto in tanto musei e mostre   
3                                       NaN 

In [132]:
"""
communityModel = CommunityModel(perspective, daoRoute = 'data/processed/GAM user_interactions.json')
communityModel = CommunityModel(perspective, daoRoute = 'data/GAM user_interactions.json')
communityModel = CommunityModel(perspective, daoRoute = 'data/annotated-stories.json')
"""

"\ncommunityModel = CommunityModel(perspective, daoRoute = 'data/processed/GAM user_interactions.json')\ncommunityModel = CommunityModel(perspective, daoRoute = 'data/GAM user_interactions.json')\ncommunityModel = CommunityModel(perspective, daoRoute = 'data/annotated-stories.json')\n"

In [133]:
communityModel = CommunityModel(perspective, dao = daoJson)

In [134]:
# Experiment with different percentages (0,1, 0.3, 0.5, 0.7, 0.9)
p = 0.5

In [135]:
communityModel.start(percentageExplainability = p)

distance matrix route
C:\Users\espil\Documents\GitHub\community-model-api-gam\server-loader\prototype-clustering\communityModel\distanceMatrix\GAM similar user plutchik emotions in similar artworks (iconclass).json
distance matrix clustering file doesnt exist
abspath: C:\Users\espil\Documents\GitHub\community-model-api-gam\server-loader\prototype-clustering\community_module\similarity
relpath: ../../communityModel/data/GAM_Catalogue_plus.json
route: C:\Users\espil\Documents\GitHub\community-model-api-gam\server-loader\prototype-clustering\communityModel\data\GAM_Catalogue_plus.json
[[ 1.  1.  1.  1.  2.  1. 15.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  2.  1. 15.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  2.  1. 15.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  2.  1. 15.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2. 15.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 1.  1.  1.  1.  2.  1. 15.  1.  1.  1.  1.  1.  2.  1

In [136]:
from os import listdir
from os import getcwd
from os.path import isfile, join

path = r"perspectives/GAM LDH/"
onlyfiles = [f for f in listdir(path) if isfile(join(path, f))]

perspective = ""
i = 0
for filename in onlyfiles:
    i = i + 1
    ## Saltar ficheros
    # if any([att_name for att_name in ["sentiments"] if att_name in filename]):
    #     print("El fichero '", filename, "' se salto")
    #     continue
    print("File: [", i, "of", len(onlyfiles), "]")
    try:
        with open(path + filename, 'r', encoding='utf8') as f:
            perspective = json.load(f)
        ###
        daoJson = DAO_json('data/generated/GAM user_interactions mergedArtworks.json')
        df = daoJson.getPandasDataframe()
        ###
        # communityModel = CommunityModel(perspective, dao = daoJson)
        ###
        # Experiment with different percentages (0,1, 0.3, 0.5, 0.7, 0.9)
        for p in [0,1, 0.3, 0.5, 0.7, 0.9]:
            print("[p =", p,"]")
            communityModel = CommunityModel(perspective, dao = daoJson)
            communityModel.start(percentageExplainability = p)
    except Exception as e:
        print(e)
        print("Filename: ", path + filename)
        raise e
        break

File: [ 1 of 12 ]
[p = 0 ]
distance matrix route
C:\Users\espil\Documents\GitHub\community-model-api-gam\server-loader\prototype-clustering\communityModel\distanceMatrix\GAM similar user emotions in similar artworks (artist_country).json
distance matrix clustering file doesnt exist
abspath: C:\Users\espil\Documents\GitHub\community-model-api-gam\server-loader\prototype-clustering\community_module\similarity
relpath: ../../communityModel/data/GAM_Catalogue_plus.json
route: C:\Users\espil\Documents\GitHub\community-model-api-gam\server-loader\prototype-clustering\communityModel\data\GAM_Catalogue_plus.json
[[ 1. 11.  1.  1.  2.  1.  1.  1.]
 [11. 11. 11. 11. 11. 11. 11. 11.]
 [ 1. 11.  1.  1.  2.  1.  1.  1.]
 [ 1. 11.  1.  1.  2.  1.  1.  1.]
 [ 2. 11.  2.  2.  2.  2.  2.  2.]
 [ 1. 11.  1.  1.  2.  1.  1.  1.]
 [ 1. 11.  1.  1.  2.  1.  1.  1.]
 [ 1. 11.  1.  1.  2.  1.  1.  1.]]
algorithm: <class 'community_module.community_detection.agglomerativeCommunityDetection.AgglomerativeCommun