In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import json

In [3]:
users = pd.read_json('data/GAMGame_users_RN_UNITO (english).json')
users

_id  userName          TimeStamps                       Gender  \
0   ESgjVz8z  ESgjVz8z 2022-01-10 16:11:35                      Femmina   
1   FVhf7OMw  FVhf7OMw 2022-01-10 17:20:13                      Femmina   
2   KQTGApjD  KQTGApjD 2022-01-10 16:59:07                      Femmina   
3   EjiUsK4q  EjiUsK4q 2022-01-10 14:50:52                      Femmina   
4   Qznzzgyq  Qznzzgyq 2022-01-10 17:05:36                      Maschio   
5   g1TFBL2O  g1TFBL2O 2022-01-10 14:01:37                      Femmina   
6   wr3s3Q8I  wr3s3Q8I 2022-01-10 11:49:59  Preferisco non specificarlo   
7   9OxdrHr9  9OxdrHr9 2022-01-10 15:55:41                      Maschio   
8   8bo9vRya  8bo9vRya 2022-01-10 11:55:06                      Maschio   
9   Sz5Wx2XD  Sz5Wx2XD 2022-01-10 17:47:27                      Maschio   
10  xTeGAzfh  xTeGAzfh 2022-01-10 12:25:42                      Maschio   
11  tLNZGrnb  tLNZGrnb 2022-01-10 15:17:04                      Maschio   
12  ILGC7yoM  ILGC7yoM 2022-01-10 16:24:16                      Maschio   
13  Y0WXF1LR  Y0WXF1LR 2022-01-10 17:21:17                      Femmina   
14  RQ4a2nIG  RQ4a2nIG 2022-01-10 11:21:12  Preferisco non specificarlo   
15  yjlouq5U  yjlouq5U 2022-01-10 17:20:01                      Femmina   
16  hIYpFFD9  hIYpFFD9 2022-01-10 12:24:31  Preferisco non specificarlo   
17  qh52qWvy  qh52qWvy 2022-01-10 23:09:53                      Femmina   
18  WsK2A1ab  WsK2A1ab 2022-01-10 14:56:53                      Maschio   
19  rh2ouJ8K  rh2ouJ8K 2022-01-10 18:00:56                      Maschio   
20  H4HTW2fP  H4HTW2fP 2022-01-10 17:18:29                      Femmina   
21  zZbRbDHJ  zZbRbDHJ 2022-01-10 16:39:52                      Maschio   
22  IxWPl3jn  IxWPl3jn 2022-01-10 15:55:01                      Femmina   
23  Ze8j8vow  Ze8j8vow 2022-01-10 13:34:27                      Femmina   
24  cBjFhvjx  cBjFhvjx 2022-01-10 16:58:18                      Maschio   
25  WYCImqGm  WYCImqGm 2022-01-10 15:54:48                      Femmina   
26  oLIVkH63  oLIVkH63 2022-01-10 15:16:59                      Femmina   
27  Z0Yh1OKl  Z0Yh1OKl 2022-01-10 15:35:09                      Femmina   
28  yPwQH2dv  yPwQH2dv 2022-01-10 13:26:19                      Maschio   
29  B3N0HGw4  B3N0HGw4 2022-01-10 17:07:46                      Femmina   
30  xLKHQujh  xLKHQujh 2022-01-10 18:03:43                      Femmina   
31  x2AUnHqw  x2AUnHqw 2022-01-10 15:45:38                      Femmina   
32  ON7PiJDX  ON7PiJDX 2022-01-10 16:38:40                      Femmina   
33  L1IvV8Lh  L1IvV8Lh 2022-01-10 17:30:14                      Femmina   
34  DaG3ihhE  DaG3ihhE 2022-01-10 17:49:47                      Maschio   
35  ihf3UjPQ  ihf3UjPQ 2022-01-10 17:12:06                      Maschio   
36  Prg8AFA8  Prg8AFA8 2022-01-10 12:25:31                      Maschio   
37  q2BDj1os  q2BDj1os 2022-01-10 15:15:45                      Maschio   
38  iuIdJidm  iuIdJidm 2022-01-10 15:54:56                      Femmina   
39  JgevtrSb  JgevtrSb 2022-09-30 11:16:16  Preferisco non specificarlo   
40  Z6UTqfYi  Z6UTqfYi 2022-01-10 18:28:38                      Maschio   
41  2fCGLTjm  2fCGLTjm 2022-01-10 17:36:47                      Maschio   
42  LvIeXwcT  LvIeXwcT 2022-01-10 10:53:03  Preferisco non specificarlo   
43  onDqgFnI  onDqgFnI 2022-01-10 16:58:57                      Maschio   
44  kaNZpdGB  kaNZpdGB 2022-01-10 17:11:59                      Femmina   
45  iVdIlHNA  iVdIlHNA 2022-01-10 17:31:58                      Maschio   
46  ZWrgWx9o  ZWrgWx9o 2022-01-10 14:06:45                      Maschio   
47  QdVgPjFx  QdVgPjFx 2022-01-10 11:47:54                      Femmina   
48  N72IRgFy  N72IRgFy 2022-01-10 16:23:52                      Maschio   
49  8sAIqaGe  8sAIqaGe 2022-01-10 17:50:04                      Femmina   
50  LW3Klzvx  LW3Klzvx 2022-01-10 17:09:19                      Femmina   
51  loEoYm9R  loEoYm9R 2022-01-10 15:54:48                      Femmina   
52  3iCAAMo9  3iCAAMo9 2022-01-10 

In [4]:
artworks = pd.read_json('data/GAM_Catalogue_plus.json')
artworks

_id    @id  DateOfLastModify  \
0   35246  35246  2019-01-15 11:52   
1   35211  35211  2015-12-18 12:50   
2   35250  35250  2018-12-05 12:24   
3   35381  35381  2015-12-21 11:39   
4   35456  35456  2019-01-15 10:59   
5   35499  35499  2017-04-18 16:33   
6   35362  35362  2020-11-30 16:19   
7   35227  35227  2020-12-11 17:05   
8   35323  35323  2018-04-17 17:06   
9   35374  35374  2018-11-23 09:54   
10  35237  35237  2018-11-19 09:58   
11  35210  35210  2018-11-19 12:23   
12  35230  35230  2018-04-17 17:02   
13  35288  35288  2018-11-14 12:47   
14  39182  39182  2018-12-11 11:01   
15  35217  35217  2018-11-13 10:07   
16  39648  39648  2020-11-30 17:07   
17  39384  39384  2020-12-11 16:11   
18  35364  35364  2018-11-20 09:40   
19  39347  39347  2019-01-24 13:28   
20  35433  35433  2018-11-14 10:27   
21  35236  35236  2018-12-07 10:47   
22  41209  41209  2020-06-18 14:29   
23  35308  35308  2018-11-13 11:40   
24  39425  39425  2020-11-30 17:21   
25  35279  35279  2018-11-23 09:37   
26  35445  35445  2015-12-21 12:14   
27  39427  39427  2020-11-30 17:19   
28  39426  39426  2020-11-30 17:20   
29  39200  39200  2018-12-14 15:04   
30  35330  35330  2018-12-13 11:41   
31  39352  39352  2019-01-25 11:11   
32  39364  39364  2019-01-28 12:33   
33  35310  35310  2019-01-15 10:44   
34  35412  35412  2018-11-14 14:08   
35  35287  35287  2018-11-23 09:41   
36  35229  35229  2019-01-15 11:48   
37  35213  35213  2019-01-15 10:46   
38  35465  35465  2018-11-07 11:50   
39  35222  35222  2018-11-19 09:42   
40  35321  35321  2018-04-17 17:05   
41  35225  35225  2018-11-19 09:43   
42  35360  35360  2018-11-23 10:04   
43  35209  35209  2018-11-19 09:41   
44  39416  39416  2020-11-30 17:33   
45  35459  35459  2019-01-15 10:52   
46  39138  39138  2018-11-14 13:28   
47  35232  35232  2018-12-05 11:14   
48  35233  35233  2019-01-15 10:32   
49  39175  39175  2020-04-24 10:45   
50  35249  35249  2018-04-17 16:51   
51  35567  35567  2018-04-17 17:01   
52  35208  35208  2018-11-15 11:42   
53  35224  35224  2018-04-19 16:07   
54  35245  35245  2018-11-20 12:52   
55  35212  35212  2018-11-19 12:39   

                                                Title Inventary  \
0                                  Mafai con il gatto    FD/323   
1                 Bimba dormente (Bimba addormentata)      S/55   
2               Abstraction with Brown Burlap (Sacco)    P/1728   
3                       Autoritratto in forma di gufo    P/1571   
4                                         La pittrice    P/1955   
5                                              Estate             
6                                    Capanni sul mare     P/997   
7                                   Contadini al sole     P/965   
8                          Daphne (Daphne a Pavarolo)    P/1079   
9                                        La primavera    FD/328   
10                                          L'aratura    P/1837   
11      Paesaggio con cascata (Sottobosco con monaco)   fl/2189   
12                                          Le baiser    P/1838   
13                         Mercato Vecchio di Firenze     P/790   
14                                             Aracne     P/480   
15                    La femme de Claude (L'adultera)     P/408   
16      Anticoli sole a picco (Paesaggio di Anticoli)    P/1114   
17                                             Marina    P/1833   
18                                          Maternità     S/164   
19                                      Dans mon pays    P/1321   
20                  Ritorno alla stalla (La ritirata)     P/374   
21                          Intervista con la materia  FD / 174   
22                107. Aktion (prima e seconda parte)             
23                Un Natale! Al Pio Albergo Trivulzio     P/907   
24                                    Strada laterale    P/2318   
25                              I funerali di Tiziano     P/524   
26                            

In [1]:
interactions = pd.read_json('data/GAMGame_stories_RN_UNITO.json')
interactions

NameError: name 'pd' is not defined

In [6]:
#--------------------------------------------------------------------------------------------------------------------------
#    Remove interactions without a valid artwork
#--------------------------------------------------------------------------------------------------------------------------


In [7]:
print(pd.unique(interactions['IdArtefact']))
print(len(pd.unique(interactions['IdArtefact'])))

[35245 35215 35230 35224 35222 35249 35256 41209 39175 35433 39352 35400
 39416 35364 35217 35287 39425 35229 39182 35307 39427 35330 39347 35445
 35459 39138 35323 35567 39200 35221 35227 35360 39384 39648 35362 41213
 35412 35225 35246 35288 39426 35380 39364 35456 35279 35308 35310 35465
 39355 35571 35376]
51


In [8]:

df = interactions.copy()
df['IdArtefactString'] = interactions['IdArtefact']#.astype(str)
artworks['IdArtefactString'] = artworks['_id']#.astype(str)

In [9]:
df[['IdArtefactString']]

IdArtefactString
0               35245
1               35215
2               35230
3               35224
4               35222
..                ...
144             35227
145             35380
146             39364
147             35310
148             35227

[149 rows x 1 columns]

In [10]:
interactions2 = pd.merge(df,artworks, on='IdArtefactString', how='right')
interactions2.dropna(subset = ['IdArtefact'], inplace = True)
interactions2['IdArtefact'] = interactions2['IdArtefact'].astype(int)
interactions2

_id_x                   IDStory   userName  IdArtefact  \
0     64.0  6228bbcbd61ae0504b793755  anonymous       35246   
4     79.0  6331fc66eecfdb731f46e973   fqybaAk8       35456   
5    142.0  632db1bfcd877313115bb376   0bAAwK14       35456   
6    140.0  633848b362d1204a35295868   x2AUnHqw       35456   
8     61.0  63316b018e2a87630a325ade   ox8G7avH       35362   
..     ...                       ...        ...         ...   
138    5.0  62279f65330b3c372b53509e  anonymous       35224   
139   16.0  632dab3fcfb08e51f124bcef   BTKF72et       35224   
140   98.0  6331fef36fd6ef464450594e   fqybaAk8       35224   
141    1.0  62274b48110d11043b04dc94  anonymous       35245   
142   55.0  6338625f758e693b2f1aea9d   Sz5Wx2XD       35245   

               StoryTitle sessionName                        itMakesMeThinkAbout  \
0              Alessandro      storie                                        
4     Ricordi di campagna      storie                                        
5              Sensazioni      storie           mi fa pensare alla lettura   
6               Serenità       notte  attimi di riflessione in solitudine   
8                    Onde      storie                              Profumo   
..                    ...         ...                                  ...   
138     viaggi e emozioni      storie                                        
139        Quiet feelings      storie                             empathic   
140   Le forme dell"amore      storie                                        
141  preferenze estetiche      storie                                        
142      Forza potenziale       notte                     forza in potenza   

                                   ItMakesMeThinkAbout  ItRemindsMeOf  \
0                                   il gatto dici maio                  
4         una gita in campagna con mai zia che dipinge                  
5                                                                       
6                                                                       
8                                                                       
..                                                 ...            ...   
138                                         emozionata                  
139  someone trying to hold on to something they no...  lost memories   
140                    quando quella notte a Parigi...                  
141                                             attesa                  
142                                                                     

                             _datasetid_x  ...  \
0    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
4    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
5    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
6    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
8    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
..                                    ...  ...   
138  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
139  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
140  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
141  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
142  cf5a766e-4d92-4946-b975-eb613a40969b  ...   

                           Iconclass_subjects_curators  \
0    31D14 adult man; 33A14 embracing each other; 3...   
4    25HH113 (high) hill - HH - ideal landscapes; 2...   
5    25HH113 (high) hill - HH - ideal landscapes; 2...   
6    25HH113 (high) hill - HH - ideal landscapes; 2...   
8    25HH2322 sea - HH - ideal landscapes; 41A163 c...   
..                                                 ...   
138  33C233 (lovers) embracing each other, 'sympleg...   
139  33C233 (lovers) embracing each other, 'sympleg...   
140  33C233 (lovers) embracing each other, 'sympleg...   
141  31D12 youth, young man, adolescent; 31D12(+51)...   
142  31D12 youth, young man, adolescent; 31D12(+51)...   

                             _datasetid_y  _timestamp_y  _timestamp_year_y  \
0    0ff7efb1-4ffa-4ed5-abc7-b9ddf895dd57    1665127

In [11]:
print(pd.unique(interactions2['IdArtefact']))
print(len(pd.unique(interactions2['IdArtefact'])))

[35246 35456 35362 35227 35323 35230 35288 39182 35217 39648 39384 35364
 39347 35433 41209 35308 39425 35279 35445 39427 39426 39200 35330 39352
 39364 35310 35412 35287 35229 35465 35222 35225 35360 39416 35459 39138
 39175 35249 35567 35224 35245]
41


In [12]:
#--------------------------------------------------------------------------------------------------------------------------
#    Merge with user data (to obtain demographics)
#--------------------------------------------------------------------------------------------------------------------------


In [13]:
interactions2

_id_x                   IDStory   userName  IdArtefact  \
0     64.0  6228bbcbd61ae0504b793755  anonymous       35246   
4     79.0  6331fc66eecfdb731f46e973   fqybaAk8       35456   
5    142.0  632db1bfcd877313115bb376   0bAAwK14       35456   
6    140.0  633848b362d1204a35295868   x2AUnHqw       35456   
8     61.0  63316b018e2a87630a325ade   ox8G7avH       35362   
..     ...                       ...        ...         ...   
138    5.0  62279f65330b3c372b53509e  anonymous       35224   
139   16.0  632dab3fcfb08e51f124bcef   BTKF72et       35224   
140   98.0  6331fef36fd6ef464450594e   fqybaAk8       35224   
141    1.0  62274b48110d11043b04dc94  anonymous       35245   
142   55.0  6338625f758e693b2f1aea9d   Sz5Wx2XD       35245   

               StoryTitle sessionName                        itMakesMeThinkAbout  \
0              Alessandro      storie                                        
4     Ricordi di campagna      storie                                        
5              Sensazioni      storie           mi fa pensare alla lettura   
6               Serenità       notte  attimi di riflessione in solitudine   
8                    Onde      storie                              Profumo   
..                    ...         ...                                  ...   
138     viaggi e emozioni      storie                                        
139        Quiet feelings      storie                             empathic   
140   Le forme dell"amore      storie                                        
141  preferenze estetiche      storie                                        
142      Forza potenziale       notte                     forza in potenza   

                                   ItMakesMeThinkAbout  ItRemindsMeOf  \
0                                   il gatto dici maio                  
4         una gita in campagna con mai zia che dipinge                  
5                                                                       
6                                                                       
8                                                                       
..                                                 ...            ...   
138                                         emozionata                  
139  someone trying to hold on to something they no...  lost memories   
140                    quando quella notte a Parigi...                  
141                                             attesa                  
142                                                                     

                             _datasetid_x  ...  \
0    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
4    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
5    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
6    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
8    cf5a766e-4d92-4946-b975-eb613a40969b  ...   
..                                    ...  ...   
138  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
139  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
140  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
141  cf5a766e-4d92-4946-b975-eb613a40969b  ...   
142  cf5a766e-4d92-4946-b975-eb613a40969b  ...   

                           Iconclass_subjects_curators  \
0    31D14 adult man; 33A14 embracing each other; 3...   
4    25HH113 (high) hill - HH - ideal landscapes; 2...   
5    25HH113 (high) hill - HH - ideal landscapes; 2...   
6    25HH113 (high) hill - HH - ideal landscapes; 2...   
8    25HH2322 sea - HH - ideal landscapes; 41A163 c...   
..                                                 ...   
138  33C233 (lovers) embracing each other, 'sympleg...   
139  33C233 (lovers) embracing each other, 'sympleg...   
140  33C233 (lovers) embracing each other, 'sympleg...   
141  31D12 youth, young man, adolescent; 31D12(+51)...   
142  31D12 youth, young man, adolescent; 31D12(+51)...   

                             _datasetid_y  _timestamp_y  _timestamp_year_y  \
0    0ff7efb1-4ffa-4ed5-abc7-b9ddf895dd57    1665127

In [14]:
# First group interaction contributions by userName
interactions_grouped = interactions2.groupby("userName").agg(list)
interactions_grouped

_id_x  \
userName                                                       
0bAAwK14                               [142.0, 106.0, 124.0]   
6rK3p7za           [73.0, 20.0, 96.0, 68.0, 15.0, 42.0, 2.0]   
B3N0HGw4                                              [94.0]   
BTKF72et                             [117.0, 4.0, 3.0, 16.0]   
JgevtrSb                                              [56.0]   
KQTGApjD                                             [100.0]   
LW3Klzvx                                              [22.0]   
LvIeXwcT                                        [48.0, 26.0]   
N72IRgFy                                              [92.0]   
RQ4a2nIG   [80.0, 147.0, 84.0, 63.0, 123.0, 82.0, 81.0, 4...   
Sz5Wx2XD                                              [55.0]   
WYCImqGm                                              [46.0]   
WsK2A1ab                                              [74.0]   
Y0WXF1LR                                             [104.0]   
ZWrgWx9o                                              [83.0]   
anonymous  [64.0, 52.0, 65.0, 78.0, 97.0, 148.0, 149.0, 6...   
cBjFhvjx                                        [50.0, 49.0]   
e4aM9WL7                                  [36.0, 35.0, 34.0]   
fqybaAk8   [79.0, 13.0, 135.0, 43.0, 121.0, 125.0, 143.0,...   
loEoYm9R                                             [144.0]   
ox8G7avH   [61.0, 30.0, 29.0, 24.0, 23.0, 32.0, 31.0, 8.0...   
q2BDj1os                                              [39.0]   
x2AUnHqw                                             [140.0]   
yjlouq5U                                               [9.0]   

                                                     IDStory  \
userName                                                       
0bAAwK14   [632db1bfcd877313115bb376, 63313ffc5484a21e957...   
6rK3p7za   [6333fd5713a6b278b06dc31b, 6333fb6713a6b278b06...   
B3N0HGw4                          [633858f82b631c1bf17add1d]   
BTKF72et   [632daf0247d0d4656c50a520, 6331680d71f6471dbc6...   
JgevtrSb                          [6239d6a43e14a72415517d5b]   
KQTGApjD                          [633857981931f9059341ba94]   
LW3Klzvx                          [6338593d2b631c1bf17add24]   
LvIeXwcT   [63370e3a45ee936df82d4d06, 63381c1708e9416c4d2...   
N72IRgFy                          [63384f412899916df970879f]   
RQ4a2nIG   [63384f33e2cc387ac313e74d, 633852356791041c9a7...   
Sz5Wx2XD                          [6338625f758e693b2f1aea9d]   
WYCImqGm                          [6338483ddf44765455526ee4]   
WsK2A1ab                          [6338389e48506113dc315697]   
Y0WXF1LR                          [63385c0def7ec10976083ec4]   
ZWrgWx9o                          [63382d748ceb081caa6ba997]   
anonymous  [6228bbcbd61ae0504b793755, 62277bd04397ce4bec2...   
cBjFhvjx   [633857663f94ba59773bc667, 633857663f94ba59773...   
e4aM9WL7   [6332e3af7f91c604d5531f59, 6332e3af7f91c604d55...   
fqybaAk8   [6331fc66eecfdb731f46e973, 6331fb30da21134eb64...   
loEoYm9R                          [63384848f689b570b53ec481]   
ox8G7avH   [63316b018e2a87630a325ade, 63316f4971f6471dbc6...   
q2BDj1os                          [63383ea41c952b2c5e786acf]   
x2AUnHqw                          [633848b362d1204a35295868]   
yjlouq5U                          [63385bb4f5bdab798a1a88a3]   

                                                  IdArtefact  \
userName                                                       
0bAAwK14                               [35456, 35230, 35287]   
6rK3p7za   [35288, 35287, 35222, 35360, 39416, 35459, 35249]   
B3N0HGw4                                             [35445]   
BTKF72et                        [35465, 35222, 35222, 35224]   
JgevtrSb                                             [39384]   
KQTGApjD                                             [35433]   
LW3Klzvx                                             [35364]   
LvIeXwcT                                      [35323, 39182]   
N72IRgFy                                             [35362]   
RQ4a2nIG   [35227, 35

In [15]:
# https://stackoverflow.com/questions/18792918/combine-two-pandas-data-frames-join-on-a-common-column
# Now merge with user data
user_interactions = pd.merge(users, interactions_grouped, on='userName', how='right')
user_interactions.dropna(subset = ['IdArtefact'], inplace = True)
user_interactions

_id   userName          TimeStamps                     Gender_x  \
0        NaN   0bAAwK14                 NaT                          NaN   
1        NaN   6rK3p7za                 NaT                          NaN   
2   B3N0HGw4   B3N0HGw4 2022-01-10 17:07:46                      Femmina   
3        NaN   BTKF72et                 NaT                          NaN   
4   JgevtrSb   JgevtrSb 2022-09-30 11:16:16  Preferisco non specificarlo   
5   KQTGApjD   KQTGApjD 2022-01-10 16:59:07                      Femmina   
6   LW3Klzvx   LW3Klzvx 2022-01-10 17:09:19                      Femmina   
7   LvIeXwcT   LvIeXwcT 2022-01-10 10:53:03  Preferisco non specificarlo   
8   N72IRgFy   N72IRgFy 2022-01-10 16:23:52                      Maschio   
9   RQ4a2nIG   RQ4a2nIG 2022-01-10 11:21:12  Preferisco non specificarlo   
10  Sz5Wx2XD   Sz5Wx2XD 2022-01-10 17:47:27                      Maschio   
11  WYCImqGm   WYCImqGm 2022-01-10 15:54:48                      Femmina   
12  WsK2A1ab   WsK2A1ab 2022-01-10 14:56:53                      Maschio   
13  Y0WXF1LR   Y0WXF1LR 2022-01-10 17:21:17                      Femmina   
14  ZWrgWx9o   ZWrgWx9o 2022-01-10 14:06:45                      Maschio   
15       NaN  anonymous                 NaT                          NaN   
16  cBjFhvjx   cBjFhvjx 2022-01-10 16:58:18                      Maschio   
17       NaN   e4aM9WL7                 NaT                          NaN   
18       NaN   fqybaAk8                 NaT                          NaN   
19  loEoYm9R   loEoYm9R 2022-01-10 15:54:48                      Femmina   
20       NaN   ox8G7avH                 NaT                          NaN   
21  q2BDj1os   q2BDj1os 2022-01-10 15:15:45                      Maschio   
22  x2AUnHqw   x2AUnHqw 2022-01-10 15:45:38                      Femmina   
23  yjlouq5U   yjlouq5U 2022-01-10 17:20:01                      Femmina   

                            Age           RelationshipWithArt  \
0                           NaN                              NaN   
1                           NaN                              NaN   
2                    20-30 anni  I have a strong interest in art   
3                           NaN                              NaN   
4                         45-60  I have a strong interest in art   
5                    20-30 anni          Art interests me little   
6                    20-30 anni          Art interests me little   
7                         45-60        I have no interest in art   
8                    13-19 anni          Art interests me little   
9   Preferisco non specificarlo        I have no interest in art   
10                   20-30 anni  I have a strong interest in art   
11                   20-30 anni  I have a strong interest in art   
12                    più di 60          Art interests me little   
13                    più di 60             My work is about art   
14                   20-30 anni  I have a strong interest in art   
15                          NaN                              NaN   
16                   20-30 anni  I have a strong interest in art   
17                          NaN                              NaN   
18                          NaN                              NaN   
19                   20-30 anni          Art interests me little   
20                          NaN                              NaN   
21                        45-60  I have a strong interest in art   
22                   20-30 anni          Art interests me little   
23                   20-30 anni  I have a strong interest in art   

                            RelationshipWithMuseum  \
0                                                 NaN   
1                                                 NaN   
2   I visit museums and exhibitions from time to time   
3                                                 NaN   
4                               I often visit museums   
5              I rarely visit museums and exhibitions   
6             

In [16]:
user_interactions.columns

Index(['_id', 'userName', 'TimeStamps', 'Gender_x', 'Age',
       'RelationshipWithArt', 'RelationshipWithMuseum',
       'content_breaking', '_datasetid', '_timestamp', '_timestamp_year',
       '_timestamp_month', '_timestamp_day', '_timestamp_hour',
       '_timestamp_minute', '_timestamp_second', '_updated', '_id_x',
       'IDStory', 'IdArtefact', 'StoryTitle', 'sessionName', 'itMakesMeThinkAbout',
       'ItMakesMeThinkAbout', 'ItRemindsMeOf', '_datasetid_x', '_timestamp_x',
       '_timestamp_year_x', '_timestamp_month_x', '_timestamp_day_x',
       '_timestamp_hour_x', '_timestamp_minute_x', '_timestamp_second_x',
       '_updated_x', 'emotions', 'sentiment', 'toxicity', 'entities',
       'plutchik_emotions', 'senticnet_emotion_recognition',
       'senticnet_concept_parsing', 'senticnet_subjectivity_detection',
       'senticnet_polarity_classification', 'senticnet_intensity_ranking',
       'senticnet_aspect_extraction', 'senticnet_personality_prediction',
       'senticnet_

In [17]:
# https://stackoverflow.com/questions/50404559/python-error-typeerror-object-of-type-timestamp-is-not-json-serializable
str1 = '_timestamp'
options1 = ['x','y']
options2 = ['day','month','year','hour','minute','second']
columns = []
for option1 in options1:
    columns.append(str1 + '_' + option1)
    for option2 in options2:
        columns.append(str1 + '_' + option2 + '_' + option1)
columns.append('TimeStamps')
columns



['_timestamp_x',
 '_timestamp_day_x',
 '_timestamp_month_x',
 '_timestamp_year_x',
 '_timestamp_hour_x',
 '_timestamp_minute_x',
 '_timestamp_second_x',
 '_timestamp_y',
 '_timestamp_day_y',
 '_timestamp_month_y',
 '_timestamp_year_y',
 '_timestamp_hour_y',
 '_timestamp_minute_y',
 '_timestamp_second_y',
 'TimeStamps']

In [18]:
user_interactions_save = user_interactions.copy()
user_interactions_save[columns] = user_interactions_save[columns].astype(str)
#user_interactions_save.drop(columns, axis = 1)
user_interactions_save


_id   userName           TimeStamps                     Gender_x  \
0        NaN   0bAAwK14                  NaT                          NaN   
1        NaN   6rK3p7za                  NaT                          NaN   
2   B3N0HGw4   B3N0HGw4  2022-01-10 17:07:46                      Femmina   
3        NaN   BTKF72et                  NaT                          NaN   
4   JgevtrSb   JgevtrSb  2022-09-30 11:16:16  Preferisco non specificarlo   
5   KQTGApjD   KQTGApjD  2022-01-10 16:59:07                      Femmina   
6   LW3Klzvx   LW3Klzvx  2022-01-10 17:09:19                      Femmina   
7   LvIeXwcT   LvIeXwcT  2022-01-10 10:53:03  Preferisco non specificarlo   
8   N72IRgFy   N72IRgFy  2022-01-10 16:23:52                      Maschio   
9   RQ4a2nIG   RQ4a2nIG  2022-01-10 11:21:12  Preferisco non specificarlo   
10  Sz5Wx2XD   Sz5Wx2XD  2022-01-10 17:47:27                      Maschio   
11  WYCImqGm   WYCImqGm  2022-01-10 15:54:48                      Femmina   
12  WsK2A1ab   WsK2A1ab  2022-01-10 14:56:53                      Maschio   
13  Y0WXF1LR   Y0WXF1LR  2022-01-10 17:21:17                      Femmina   
14  ZWrgWx9o   ZWrgWx9o  2022-01-10 14:06:45                      Maschio   
15       NaN  anonymous                  NaT                          NaN   
16  cBjFhvjx   cBjFhvjx  2022-01-10 16:58:18                      Maschio   
17       NaN   e4aM9WL7                  NaT                          NaN   
18       NaN   fqybaAk8                  NaT                          NaN   
19  loEoYm9R   loEoYm9R  2022-01-10 15:54:48                      Femmina   
20       NaN   ox8G7avH                  NaT                          NaN   
21  q2BDj1os   q2BDj1os  2022-01-10 15:15:45                      Maschio   
22  x2AUnHqw   x2AUnHqw  2022-01-10 15:45:38                      Femmina   
23  yjlouq5U   yjlouq5U  2022-01-10 17:20:01                      Femmina   

                            Age           RelationshipWithArt  \
0                           NaN                              NaN   
1                           NaN                              NaN   
2                    20-30 anni  I have a strong interest in art   
3                           NaN                              NaN   
4                         45-60  I have a strong interest in art   
5                    20-30 anni          Art interests me little   
6                    20-30 anni          Art interests me little   
7                         45-60        I have no interest in art   
8                    13-19 anni          Art interests me little   
9   Preferisco non specificarlo        I have no interest in art   
10                   20-30 anni  I have a strong interest in art   
11                   20-30 anni  I have a strong interest in art   
12                    più di 60          Art interests me little   
13                    più di 60             My work is about art   
14                   20-30 anni  I have a strong interest in art   
15                          NaN                              NaN   
16                   20-30 anni  I have a strong interest in art   
17                          NaN                              NaN   
18                          NaN                              NaN   
19                   20-30 anni          Art interests me little   
20                          NaN                              NaN   
21                        45-60  I have a strong interest in art   
22                   20-30 anni          Art interests me little   
23                   20-30 anni  I have a strong interest in art   

                            RelationshipWithMuseum  \
0                                                 NaN   
1                                                 NaN   
2   I visit museums and exhibitions from time to time   
3                                                 NaN   
4                               I often visit museums   
5              I rarely visit museums and exhi

In [19]:
# Change NaN values for demographics data (RelationshipWithArt, RelationshipWithMuseum)
values = {'RelationshipWithArt':  'unknown', 'RelationshipWithMuseum': 'unknown'}
user_interactions_save2 = user_interactions_save.fillna(value=values)
user_interactions_save2


_id   userName           TimeStamps                     Gender_x  \
0        NaN   0bAAwK14                  NaT                          NaN   
1        NaN   6rK3p7za                  NaT                          NaN   
2   B3N0HGw4   B3N0HGw4  2022-01-10 17:07:46                      Femmina   
3        NaN   BTKF72et                  NaT                          NaN   
4   JgevtrSb   JgevtrSb  2022-09-30 11:16:16  Preferisco non specificarlo   
5   KQTGApjD   KQTGApjD  2022-01-10 16:59:07                      Femmina   
6   LW3Klzvx   LW3Klzvx  2022-01-10 17:09:19                      Femmina   
7   LvIeXwcT   LvIeXwcT  2022-01-10 10:53:03  Preferisco non specificarlo   
8   N72IRgFy   N72IRgFy  2022-01-10 16:23:52                      Maschio   
9   RQ4a2nIG   RQ4a2nIG  2022-01-10 11:21:12  Preferisco non specificarlo   
10  Sz5Wx2XD   Sz5Wx2XD  2022-01-10 17:47:27                      Maschio   
11  WYCImqGm   WYCImqGm  2022-01-10 15:54:48                      Femmina   
12  WsK2A1ab   WsK2A1ab  2022-01-10 14:56:53                      Maschio   
13  Y0WXF1LR   Y0WXF1LR  2022-01-10 17:21:17                      Femmina   
14  ZWrgWx9o   ZWrgWx9o  2022-01-10 14:06:45                      Maschio   
15       NaN  anonymous                  NaT                          NaN   
16  cBjFhvjx   cBjFhvjx  2022-01-10 16:58:18                      Maschio   
17       NaN   e4aM9WL7                  NaT                          NaN   
18       NaN   fqybaAk8                  NaT                          NaN   
19  loEoYm9R   loEoYm9R  2022-01-10 15:54:48                      Femmina   
20       NaN   ox8G7avH                  NaT                          NaN   
21  q2BDj1os   q2BDj1os  2022-01-10 15:15:45                      Maschio   
22  x2AUnHqw   x2AUnHqw  2022-01-10 15:45:38                      Femmina   
23  yjlouq5U   yjlouq5U  2022-01-10 17:20:01                      Femmina   

                            Age           RelationshipWithArt  \
0                           NaN                          unknown   
1                           NaN                          unknown   
2                    20-30 anni  I have a strong interest in art   
3                           NaN                          unknown   
4                         45-60  I have a strong interest in art   
5                    20-30 anni          Art interests me little   
6                    20-30 anni          Art interests me little   
7                         45-60        I have no interest in art   
8                    13-19 anni          Art interests me little   
9   Preferisco non specificarlo        I have no interest in art   
10                   20-30 anni  I have a strong interest in art   
11                   20-30 anni  I have a strong interest in art   
12                    più di 60          Art interests me little   
13                    più di 60             My work is about art   
14                   20-30 anni  I have a strong interest in art   
15                          NaN                          unknown   
16                   20-30 anni  I have a strong interest in art   
17                          NaN                          unknown   
18                          NaN                          unknown   
19                   20-30 anni          Art interests me little   
20                          NaN                          unknown   
21                        45-60  I have a strong interest in art   
22                   20-30 anni          Art interests me little   
23                   20-30 anni  I have a strong interest in art   

                            RelationshipWithMuseum  \
0                                             unknown   
1                                             unknown   
2   I visit museums and exhibitions from time to time   
3                                             unknown   
4                               I often visit museums   
5              I rarely visit museums and exhi

In [20]:
with open("data/generated/GAM user_interactions mergedArtworks.json", "w") as outfile:
    json.dump(user_interactions_save2.to_dict('records'), outfile, indent=4)

In [21]:
# Remove anonymous users
user_interactions_save3 = user_interactions_save2.loc[user_interactions_save2['userName'] != 'anonymous']
user_interactions_save3

_id  userName           TimeStamps                     Gender_x  \
0        NaN  0bAAwK14                  NaT                          NaN   
1        NaN  6rK3p7za                  NaT                          NaN   
2   B3N0HGw4  B3N0HGw4  2022-01-10 17:07:46                      Femmina   
3        NaN  BTKF72et                  NaT                          NaN   
4   JgevtrSb  JgevtrSb  2022-09-30 11:16:16  Preferisco non specificarlo   
5   KQTGApjD  KQTGApjD  2022-01-10 16:59:07                      Femmina   
6   LW3Klzvx  LW3Klzvx  2022-01-10 17:09:19                      Femmina   
7   LvIeXwcT  LvIeXwcT  2022-01-10 10:53:03  Preferisco non specificarlo   
8   N72IRgFy  N72IRgFy  2022-01-10 16:23:52                      Maschio   
9   RQ4a2nIG  RQ4a2nIG  2022-01-10 11:21:12  Preferisco non specificarlo   
10  Sz5Wx2XD  Sz5Wx2XD  2022-01-10 17:47:27                      Maschio   
11  WYCImqGm  WYCImqGm  2022-01-10 15:54:48                      Femmina   
12  WsK2A1ab  WsK2A1ab  2022-01-10 14:56:53                      Maschio   
13  Y0WXF1LR  Y0WXF1LR  2022-01-10 17:21:17                      Femmina   
14  ZWrgWx9o  ZWrgWx9o  2022-01-10 14:06:45                      Maschio   
16  cBjFhvjx  cBjFhvjx  2022-01-10 16:58:18                      Maschio   
17       NaN  e4aM9WL7                  NaT                          NaN   
18       NaN  fqybaAk8                  NaT                          NaN   
19  loEoYm9R  loEoYm9R  2022-01-10 15:54:48                      Femmina   
20       NaN  ox8G7avH                  NaT                          NaN   
21  q2BDj1os  q2BDj1os  2022-01-10 15:15:45                      Maschio   
22  x2AUnHqw  x2AUnHqw  2022-01-10 15:45:38                      Femmina   
23  yjlouq5U  yjlouq5U  2022-01-10 17:20:01                      Femmina   

                            Age           RelationshipWithArt  \
0                           NaN                          unknown   
1                           NaN                          unknown   
2                    20-30 anni  I have a strong interest in art   
3                           NaN                          unknown   
4                         45-60  I have a strong interest in art   
5                    20-30 anni          Art interests me little   
6                    20-30 anni          Art interests me little   
7                         45-60        I have no interest in art   
8                    13-19 anni          Art interests me little   
9   Preferisco non specificarlo        I have no interest in art   
10                   20-30 anni  I have a strong interest in art   
11                   20-30 anni  I have a strong interest in art   
12                    più di 60          Art interests me little   
13                    più di 60             My work is about art   
14                   20-30 anni  I have a strong interest in art   
16                   20-30 anni  I have a strong interest in art   
17                          NaN                          unknown   
18                          NaN                          unknown   
19                   20-30 anni          Art interests me little   
20                          NaN                          unknown   
21                        45-60  I have a strong interest in art   
22                   20-30 anni          Art interests me little   
23                   20-30 anni  I have a strong interest in art   

                            RelationshipWithMuseum  \
0                                             unknown   
1                                             unknown   
2   I visit museums and exhibitions from time to time   
3                                             unknown   
4                               I often visit museums   
5              I rarely visit museums and exhibitions   
6              I rarely visit museums and exhibitions   
7              I rarely visit museums and exhibitions   
8   I visit museums and exhibitions from tim

In [22]:
with open("data/generated/GAM user_interactions mergedArtworks (not anonymous).json", "w") as outfile:
    json.dump(user_interactions_save3.to_dict('records'), outfile, indent=4)

In [18]:
#--------------------------------------------------------------------------------------------------------------------------
#    Check session
#--------------------------------------------------------------------------------------------------------------------------

In [20]:
user_interactions_save.columns

Index(['_id', 'userName', 'TimeStamps', 'Gender_x', 'Age',
       'RelationshipWithArt', 'RelationshipWithMuseum',
       'content_breaking', '_datasetid', '_timestamp', '_timestamp_year',
       '_timestamp_month', '_timestamp_day', '_timestamp_hour',
       '_timestamp_minute', '_timestamp_second', '_updated', '_id_x',
       'IDStory', 'IdArtefact', 'StoryTitle', 'sessionName', 'itMakesMeThinkAbout',
       'ItMakesMeThinkAbout', 'ItRemindsMeOf', '_datasetid_x', '_timestamp_x',
       '_timestamp_year_x', '_timestamp_month_x', '_timestamp_day_x',
       '_timestamp_hour_x', '_timestamp_minute_x', '_timestamp_second_x',
       '_updated_x', 'emotions', 'sentiment', 'toxicity', 'entities',
       'plutchik_emotions', 'senticnet_emotion_recognition',
       'senticnet_concept_parsing', 'senticnet_subjectivity_detection',
       'senticnet_polarity_classification', 'senticnet_intensity_ranking',
       'senticnet_aspect_extraction', 'senticnet_personality_prediction',
       'senticnet_

In [23]:
df = user_interactions_save.copy()
df['RelationshipWithArt'].fillna('DK',inplace=True)
df




_id   userName           TimeStamps                     Gender_x  \
0        NaN   0bAAwK14                  NaT                          NaN   
1        NaN   6rK3p7za                  NaT                          NaN   
2   B3N0HGw4   B3N0HGw4  2022-01-10 17:07:46                      Femmina   
3        NaN   BTKF72et                  NaT                          NaN   
4   JgevtrSb   JgevtrSb  2022-09-30 11:16:16  Preferisco non specificarlo   
5   KQTGApjD   KQTGApjD  2022-01-10 16:59:07                      Femmina   
6   LW3Klzvx   LW3Klzvx  2022-01-10 17:09:19                      Femmina   
7   LvIeXwcT   LvIeXwcT  2022-01-10 10:53:03  Preferisco non specificarlo   
8   N72IRgFy   N72IRgFy  2022-01-10 16:23:52                      Maschio   
9   RQ4a2nIG   RQ4a2nIG  2022-01-10 11:21:12  Preferisco non specificarlo   
10  Sz5Wx2XD   Sz5Wx2XD  2022-01-10 17:47:27                      Maschio   
11  WYCImqGm   WYCImqGm  2022-01-10 15:54:48                      Femmina   
12  WsK2A1ab   WsK2A1ab  2022-01-10 14:56:53                      Maschio   
13  Y0WXF1LR   Y0WXF1LR  2022-01-10 17:21:17                      Femmina   
14  ZWrgWx9o   ZWrgWx9o  2022-01-10 14:06:45                      Maschio   
15       NaN  anonymous                  NaT                          NaN   
16  cBjFhvjx   cBjFhvjx  2022-01-10 16:58:18                      Maschio   
17       NaN   e4aM9WL7                  NaT                          NaN   
18       NaN   fqybaAk8                  NaT                          NaN   
19  loEoYm9R   loEoYm9R  2022-01-10 15:54:48                      Femmina   
20       NaN   ox8G7avH                  NaT                          NaN   
21  q2BDj1os   q2BDj1os  2022-01-10 15:15:45                      Maschio   
22  x2AUnHqw   x2AUnHqw  2022-01-10 15:45:38                      Femmina   
23  yjlouq5U   yjlouq5U  2022-01-10 17:20:01                      Femmina   

                            Age                 RelationshipWithArt  \
0                           NaN                                     DK   
1                           NaN                                     DK   
2                    20-30 anni       Ho un forte interesse per l'arte   
3                           NaN                                     DK   
4                         45-60       Ho un forte interesse per l'arte   
5                    20-30 anni               L'arte mi interessa poco   
6                    20-30 anni               L'arte mi interessa poco   
7                         45-60  Non provo nessun interesse per l'arte   
8                    13-19 anni               L'arte mi interessa poco   
9   Preferisco non specificarlo  Non provo nessun interesse per l'arte   
10                   20-30 anni       Ho un forte interesse per l'arte   
11                   20-30 anni       Ho un forte interesse per l'arte   
12                    più di 60               L'arte mi interessa poco   
13                    più di 60          Il mio lavoro riguarda l'arte   
14                   20-30 anni       Ho un forte interesse per l'arte   
15                          NaN                                     DK   
16                   20-30 anni       Ho un forte interesse per l'arte   
17                          NaN                                     DK   
18                          NaN                                     DK   
19                   20-30 anni               L'arte mi interessa poco   
20                          NaN                                     DK   
21                        45-60       Ho un forte interesse per l'arte   
22                   20-30 anni               L'arte mi interessa poco   
23                   20-30 anni       Ho un forte interesse per l'arte   

                  RelationshipWithMuseum  \
0                                       NaN   
1                                       NaN   
2   Visito di tanto in tanto musei e mostre   
3                                       NaN   
4  

In [29]:
df2 = df.loc[df['RelationshipWithArt'] == 'DK']
df2[['userName','sessionName','RelationshipWithArt']]

userName                                        sessionName  \
0    0bAAwK14                           [storie, storie, storie]   
1    6rK3p7za  [storie, storie, storie, storie, storie, stori...   
3    BTKF72et                   [storie, storie, storie, storie]   
15  anonymous  [storie, storie, storie, storie, storie, stori...   
17   e4aM9WL7                           [storie, storie, storie]   
18   fqybaAk8  [storie, storie, storie, storie, storie, stori...   
20   ox8G7avH  [storie, storie, storie, storie, storie, stori...   

   RelationshipWithArt  
0                      DK  
1                      DK  
3                      DK  
15                     DK  
17                     DK  
18                     DK  
20                     DK

In [28]:
# Check
df = user_interactions[['userName','IdArtefact', 'plutchik_emotions']]
df

userName                                         IdArtefact  \
0    0bAAwK14                        [35456.0, 35230.0, 35287.0]   
1    6rK3p7za  [35288.0, 35287.0, 35222.0, 35360.0, 39416.0, ...   
2    B3N0HGw4                                          [35445.0]   
3    BTKF72et               [35465.0, 35222.0, 35222.0, 35224.0]   
4    JgevtrSb                                          [39384.0]   
5    KQTGApjD                                          [35433.0]   
6    LW3Klzvx                                          [35364.0]   
7    LvIeXwcT                                 [35323.0, 39182.0]   
8    N72IRgFy                                          [35362.0]   
9    RQ4a2nIG  [35227.0, 35227.0, 39182.0, 39648.0, 39648.0, ...   
10   Sz5Wx2XD                                          [35245.0]   
11   WYCImqGm                                          [35229.0]   
12   WsK2A1ab                                          [35412.0]   
13   Y0WXF1LR                                          [35323.0]   
14   ZWrgWx9o                                          [39138.0]   
15  anonymous  [35246.0, 35227.0, 35227.0, 35227.0, 35227.0, ...   
16   cBjFhvjx                                 [39175.0, 39175.0]   
17   e4aM9WL7                        [35330.0, 35330.0, 35330.0]   
18   fqybaAk8  [35456.0, 35217.0, 39425.0, 35445.0, 35287.0, ...   
19   loEoYm9R                                          [35310.0]   
20   ox8G7avH  [35362.0, 39347.0, 39347.0, 39427.0, 39427.0, ...   
21   q2BDj1os                                          [39138.0]   
22   x2AUnHqw                                          [35456.0]   
23   yjlouq5U                                          [35433.0]   

                                    plutchik_emotions  
0   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
1   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
2   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
3   [{'anger': 0, 'anticipation': 0.11111111111111...  
4   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
5   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
6   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
7   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
8   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
9   [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
10  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
11  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
12  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
13  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
14  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
15  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
16  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
17  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
18  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
19  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
20  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
21  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
22  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...  
23  [{'anger': 0, 'anticipation': 0, 'disgust': 0,...

In [20]:
#--------------------------------------------------------------------------------------------------------------------------
#    Change ageGroup
#--------------------------------------------------------------------------------------------------------------------------

In [21]:
# Change age to age groups
df = users.copy()
df.loc[df["Age"] == "20-30 anni", "Age"] = "young"
df.loc[df["Age"] == "13-19 anni", "Age"] = "young"
df.loc[df["Age"] == "31-45 anni", "Age"] = "adult"
df.loc[df["Age"] == "45-60", "Age"] = "adult"
df.loc[df["Age"] == "più di 60", "Age"] = "elderly"
df.loc[df["Age"] == "Preferisco non specificarlo", "Age"] = "DK"
users2 = df.copy()
users2

_id  userName          TimeStamps                       Gender  \
0   ESgjVz8z  ESgjVz8z 2022-01-10 16:11:35                      Femmina   
1   FVhf7OMw  FVhf7OMw 2022-01-10 17:20:13                      Femmina   
2   KQTGApjD  KQTGApjD 2022-01-10 16:59:07                      Femmina   
3   EjiUsK4q  EjiUsK4q 2022-01-10 14:50:52                      Femmina   
4   Qznzzgyq  Qznzzgyq 2022-01-10 17:05:36                      Maschio   
5   g1TFBL2O  g1TFBL2O 2022-01-10 14:01:37                      Femmina   
6   wr3s3Q8I  wr3s3Q8I 2022-01-10 11:49:59  Preferisco non specificarlo   
7   9OxdrHr9  9OxdrHr9 2022-01-10 15:55:41                      Maschio   
8   8bo9vRya  8bo9vRya 2022-01-10 11:55:06                      Maschio   
9   Sz5Wx2XD  Sz5Wx2XD 2022-01-10 17:47:27                      Maschio   
10  xTeGAzfh  xTeGAzfh 2022-01-10 12:25:42                      Maschio   
11  tLNZGrnb  tLNZGrnb 2022-01-10 15:17:04                      Maschio   
12  ILGC7yoM  ILGC7yoM 2022-01-10 16:24:16                      Maschio   
13  Y0WXF1LR  Y0WXF1LR 2022-01-10 17:21:17                      Femmina   
14  RQ4a2nIG  RQ4a2nIG 2022-01-10 11:21:12  Preferisco non specificarlo   
15  yjlouq5U  yjlouq5U 2022-01-10 17:20:01                      Femmina   
16  hIYpFFD9  hIYpFFD9 2022-01-10 12:24:31  Preferisco non specificarlo   
17  qh52qWvy  qh52qWvy 2022-01-10 23:09:53                      Femmina   
18  WsK2A1ab  WsK2A1ab 2022-01-10 14:56:53                      Maschio   
19  rh2ouJ8K  rh2ouJ8K 2022-01-10 18:00:56                      Maschio   
20  H4HTW2fP  H4HTW2fP 2022-01-10 17:18:29                      Femmina   
21  zZbRbDHJ  zZbRbDHJ 2022-01-10 16:39:52                      Maschio   
22  IxWPl3jn  IxWPl3jn 2022-01-10 15:55:01                      Femmina   
23  Ze8j8vow  Ze8j8vow 2022-01-10 13:34:27                      Femmina   
24  cBjFhvjx  cBjFhvjx 2022-01-10 16:58:18                      Maschio   
25  WYCImqGm  WYCImqGm 2022-01-10 15:54:48                      Femmina   
26  oLIVkH63  oLIVkH63 2022-01-10 15:16:59                      Femmina   
27  Z0Yh1OKl  Z0Yh1OKl 2022-01-10 15:35:09                      Femmina   
28  yPwQH2dv  yPwQH2dv 2022-01-10 13:26:19                      Maschio   
29  B3N0HGw4  B3N0HGw4 2022-01-10 17:07:46                      Femmina   
30  xLKHQujh  xLKHQujh 2022-01-10 18:03:43                      Femmina   
31  x2AUnHqw  x2AUnHqw 2022-01-10 15:45:38                      Femmina   
32  ON7PiJDX  ON7PiJDX 2022-01-10 16:38:40                      Femmina   
33  L1IvV8Lh  L1IvV8Lh 2022-01-10 17:30:14                      Femmina   
34  DaG3ihhE  DaG3ihhE 2022-01-10 17:49:47                      Maschio   
35  ihf3UjPQ  ihf3UjPQ 2022-01-10 17:12:06                      Maschio   
36  Prg8AFA8  Prg8AFA8 2022-01-10 12:25:31                      Maschio   
37  q2BDj1os  q2BDj1os 2022-01-10 15:15:45                      Maschio   
38  iuIdJidm  iuIdJidm 2022-01-10 15:54:56                      Femmina   
39  JgevtrSb  JgevtrSb 2022-09-30 11:16:16  Preferisco non specificarlo   
40  Z6UTqfYi  Z6UTqfYi 2022-01-10 18:28:38                      Maschio   
41  2fCGLTjm  2fCGLTjm 2022-01-10 17:36:47                      Maschio   
42  LvIeXwcT  LvIeXwcT 2022-01-10 10:53:03  Preferisco non specificarlo   
43  onDqgFnI  onDqgFnI 2022-01-10 16:58:57                      Maschio   
44  kaNZpdGB  kaNZpdGB 2022-01-10 17:11:59                      Femmina   
45  iVdIlHNA  iVdIlHNA 2022-01-10 17:31:58                      Maschio   
46  ZWrgWx9o  ZWrgWx9o 2022-01-10 14:06:45                      Maschio   
47  QdVgPjFx  QdVgPjFx 2022-01-10 11:47:54                      Femmina   
48  N72IRgFy  N72IRgFy 2022-01-10 16:23:52                      Maschio   
49  8sAIqaGe  8sAIqaGe 2022-01-10 17:50:04                      Femmina   
50  LW3Klzvx  LW3Klzvx 2022-01-10 17:09:19                      Femmina   
51  loEoYm9R  loEoYm9R 2022-01-10 15:54:48                      Femmina   
52  3iCAAMo9  3iCAAMo9 2022-01-10 

In [ ]:
#--------------------------------------------------------------------------------------------------------------------------
#    New interaction data (annotated-stories.json)
#--------------------------------------------------------------------------------------------------------------------------

In [37]:
annotated_stories = pd.read_json('data/provided/annotated-stories.json')
annotated_stories

_datasetid                       _id  \
0   816c8fb3-6c73-4405-bf71-b1c765c4a79e  633869df947d991ed04cf7f7   
1   816c8fb3-6c73-4405-bf71-b1c765c4a79e  633865fd947d991ed04cf7de   
2   816c8fb3-6c73-4405-bf71-b1c765c4a79e  633865ce947d991ed04cf7dc   
3   816c8fb3-6c73-4405-bf71-b1c765c4a79e  6338649a2df2fd104d686349   
4   816c8fb3-6c73-4405-bf71-b1c765c4a79e  6338625f758e693b2f1aea9d   
..                                   ...                       ...   
95  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62272bca8b5d531b7a287bc6   
96  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62272dc4aa89621f0d6ce920   
97  816c8fb3-6c73-4405-bf71-b1c765c4a79e  6227300d925cbb70f01278b4   
98  816c8fb3-6c73-4405-bf71-b1c765c4a79e  622731a552655f48ae32ca9d   
99  816c8fb3-6c73-4405-bf71-b1c765c4a79e  622738c2d74ca33e0d61f217   

    _timestamp  _timestamp_day  _timestamp_hour  _timestamp_minute  \
0   1664641503               1               17                 25   
1   1664640509               1               17                  8   
2   1664640462               1               17                  7   
3   1664640154               1               17                  2   
4   1664639583               1               16                 53   
..         ...             ...              ...                ...   
95  1656345373              27               16                 56   
96  1656345373              27               16                 56   
97  1656345373              27               16                 56   
98  1656345373              27               16                 56   
99  1656345373              27               16                 56   

    _timestamp_month  _timestamp_second  _timestamp_year  \
0                 10                  3             2022   
1                 10                 29             2022   
2                 10                 42             2022   
3                 10                 34             2022   
4                 10                  3             2022   
..               ...                ...              ...   
95                 6                 13             2022   
96                 6                 13             2022   
97                 6                 13             2022   
98                 6                 13             2022   
99                 6                 13             2022   

                  activityId authorUsername  \
0   62cc4f819f7c9c7e6739a46b       RQ4a2nIG   
1   62cc4f819f7c9c7e6739a46b       RQ4a2nIG   
2   62cc4f819f7c9c7e6739a46b       8sAIqaGe   
3   62cc4f819f7c9c7e6739a46b       RQ4a2nIG   
4   62cc4f819f7c9c7e6739a46b       Sz5Wx2XD   
..                       ...            ...   
95  620e37ba17f14811fa3ff880            NaN   
96  620e37ba17f14811fa3ff880            NaN   
97  620e37ba17f14811fa3ff880            NaN   
98  620e37ba17f14811fa3ff880            NaN   
99  620e37ba17f14811fa3ff880            NaN   

                                                parts sessionName  \
0   [{'artworkId': '39416', 'emotions': {'emotion:...       notte   
1   [{'artworkId': '39426', 'emotions': {'emotion:...       notte   
2   [{'artworkId': '35433', 'emotions': {}, 'multi...       notte   
3   [{'artworkId': '35227', 'emotions': {'marl:Pos...       notte   
4   [{'artworkId': '35571', 'emotions': {'marl:Pos...       notte   
..                                                ...         ...   
95  [{'artworkId': '35229', 'emotions': {'emotion:...         NaN   
96  [{'artworkId': '35400', 'emotions': {}, 'multi...         NaN   
97  [{'artworkId': '41214', 'emotions': {'emotion:...         NaN   
98  [{'artworkId': '35229', 'emotions': {'emotion:...         NaN   
99  [{'artworkId': '35229', 'emotions': {'emotion:...         NaN   

                   title   authorId  _updated  
0           Gli scacchi.        NaN       NaN  
1                   Vita        NaN       NaN  
2                   Casa        NaN       NaN  
3   Ritorno alle origini        NaN      

In [38]:
# Get 
annotated_stories.head(1).parts[0]

[{'artworkId': '39416',
  'emotions': {'emotion:Joy': 1.0,
   'emotion:Serenity': 0.72991085,
   'marl:Positive': 0.5606517999999999},
  'multimediaData': {'answersToTemplates': {'itMakesMeThinkAbout': '',
    'itMakesMeThinkAbout': '',
    'itRemindsMeOf': 'gli scacchi quando giocavo con mia nonna e mio nonno \n\n\n'},
   'emojis': [],
   'tags': []}},
 {'artworkId': '39416',
  'emotions': {'emotion:Interest': 1.0,
   'emotion:Joy': 1.0,
   'marl:Positive': 1.0},
  'multimediaData': {'answersToTemplates': {'itMakesMeThinkAbout': '',
    'itMakesMeThinkAbout': 'quando giocavo con la nonna e il nonno a scacchi,.\nEd era bellissimo e quando vincevo perché mi faceva sentire un professionista .',
    'itRemindsMeOf': ''},
   'emojis': [],
   'tags': []}}]

In [39]:
# Get 
annotated_stories.tail(1)

_datasetid                       _id  \
99  816c8fb3-6c73-4405-bf71-b1c765c4a79e  622738c2d74ca33e0d61f217   

    _timestamp  _timestamp_day  _timestamp_hour  _timestamp_minute  \
99  1656345373              27               16                 56   

    _timestamp_month  _timestamp_second  _timestamp_year  \
99                 6                 13             2022   

                  activityId authorUsername  \
99  620e37ba17f14811fa3ff880            NaN   

                                                parts sessionName     title  \
99  [{'artworkId': '35229', 'emotions': {'emotion:...         NaN  my story   

     authorId  _updated  
99  anonymous       1.0

In [40]:
annotated_stories[annotated_stories['authorId'] == 'anonymous']

_datasetid                       _id  \
82  816c8fb3-6c73-4405-bf71-b1c765c4a79e  63217cfea21ff73cac05bf8b   
83  816c8fb3-6c73-4405-bf71-b1c765c4a79e  63217c433995b21ef1393057   
84  816c8fb3-6c73-4405-bf71-b1c765c4a79e  632178935d6a786add2e128e   
85  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62cd9a60acd3771b6079f40c   
86  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62c2eb090c1f35613850f546   
87  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62c2e98dffb9c536f1006870   
88  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62bdd2020af3e135fc5753bc   
89  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62bc1ba12f07457bfe735ff1   
90  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62756099cd7c212a137326cb   
94  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62267c7a02738d5dc9508438   
95  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62272bca8b5d531b7a287bc6   
96  816c8fb3-6c73-4405-bf71-b1c765c4a79e  62272dc4aa89621f0d6ce920   
97  816c8fb3-6c73-4405-bf71-b1c765c4a79e  6227300d925cbb70f01278b4   
98  816c8fb3-6c73-4405-bf71-b1c765c4a79e  622731a552655f48ae32ca9d   
99  816c8fb3-6c73-4405-bf71-b1c765c4a79e  622738c2d74ca33e0d61f217   

    _timestamp  _timestamp_day  _timestamp_hour  _timestamp_minute  \
82  1663139070              14                8                  4   
83  1663138883              14                8                  1   
84  1663137939              14                7                 45   
85  1657641568              12               16                 59   
86  1656941321               4               14                 28   
87  1656940941               4               14                 22   
88  1656607234              30               17                 40   
89  1656495009              29               10                 30   
90  1656345374              27               16                 56   
94  1656345373              27               16                 56   
95  1656345373              27               16                 56   
96  1656345373              27               16                 56   
97  1656345373              27               16                 56   
98  1656345373              27               16                 56   
99  1656345373              27               16                 56   

    _timestamp_month  _timestamp_second  _timestamp_year  \
82                 9                 30             2022   
83                 9                 23             2022   
84                 9                 39             2022   
85                 7                 28             2022   
86                 7                 41             2022   
87                 7                 21             2022   
88                 6                 34             2022   
89                 6                  9             2022   
90                 6                 14             2022   
94                 6                 13             2022   
95                 6                 13             2022   
96                 6                 13             2022   
97                 6                 13             2022   
98                 6                 13             2022   
99                 6                 13             2022   

                  activityId authorUsername  \
82  62cc4f819f7c9c7e6739a46b            NaN   
83  62cc4f819f7c9c7e6739a46b            NaN   
84  62cc4f819f7c9c7e6739a46b            NaN   
85  6227632cc632154a7316e211            NaN   
86  6227632cc632154a7316e211            NaN   
87  6227632cc632154a7316e211            NaN   
88  6227632cc632154a7316e211            NaN   
89  62274a86acb5022a767ca00c            NaN   
90  6227632cc632154a7316e211            NaN   
94  620e37ba17f14811fa3ff880            NaN   
95  620e37ba17f14811fa3ff880            NaN   
96  620e37ba17f14811fa3ff880            NaN   
97  620e37ba17f14811fa3ff880            NaN   
98  620e37ba17f14811fa3ff880            NaN   
99  620e37ba17f14811fa3ff880            NaN   

                                                parts sessionName  \
82  [

In [22]:
#--------------------------------------------------------------------------------------------------------------------------
#    Distance matrix
#--------------------------------------------------------------------------------------------------------------------------

In [23]:
from context import community_module, dao, communityModel

In [24]:
from communityModel.communityModel import CommunityModel
from communityModel.artworkModel import ArtworkModel
from dao.dao_json import DAO_json

In [25]:
# Perspective (user attributes, artworks similarity features, emotion similarity on plutchik emotions similar artworks)
with open('perspectives/perspective gam.json', 'r', encoding='utf8') as f:
    perspective = json.load(f)[0]
perspective

{'id': 'gam-agglomerative',
 'name': 'GAM (agglomerative)',
 'algorithm': {'name': 'agglomerative', 'params': []},
 'similarity_functions': [{'sim_function': {'name': 'IconClassSimilarityDAO',
    'params': [],
    'on_attribute': {'att_name': 'Iconclass_subjects_curators',
     'att_type': 'String'},
    'weight': 0.8}}],
 'user_attributes': [{'att_name': 'RelationshipWithArt',
   'att_type': 'String'},
  {'att_name': 'RelationshipWithMuseum', 'att_type': 'String'}],
 'interaction_similarity_functions': [{'sim_function': {'name': 'PlutchikEmotionSimilarityDAO',
    'params': [],
    'on_attribute': {'att_name': 'emotions', 'att_type': 'dict'},
    'interaction_object': {'att_name': 'IdArtefact',
     'att_type': 'String',
     'mode': 'similar'}}}]}

In [26]:
# Call Artwork model (calculates similarity between artworks)
artworkModel = ArtworkModel(perspective)

In [27]:
daoJson = DAO_json('data/GAM_Catalogue_plus.json')
similarityMeasure = artworkModel.initializeComplexSimilarityMeasure(daoJson)
similarityMeasure

In [28]:
distanceMatrix = artworkModel.computeDistanceMatrix()
distanceMatrix

elemA: 20
elemB: 20
Iconclass A: ['41A161', '26B', '26A32', '47I213', '47I2211', '47I22111', '47I221']
Iconclass B: ['41A161', '26B', '26A32', '47I213', '47I2211', '47I22111', '47I221']


distance 41A161 : 0.0
distance 26B : 0.0
distance 26A32 : 0.0
distance 47I213 : 0.0
distance 47I2211 : 0.0
distance 47I22111 : 0.0
distance 47I221 : 0.0
distanceTotal: 0.0


array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [29]:
# Export _id (id artefact) and distance matrix to json file
jsonObject = {}
jsonObject['index'] = similarityMeasure.data['_id'].tolist()
jsonObject['distanceMatrix'] = distanceMatrix.tolist()
jsonObject
"b"

'b'

In [30]:
with open("interactionObjects/GAM artwork iconclass Notebook.json", "w") as outfile:
    json.dump(jsonObject, outfile, indent=4)

In [31]:
#--------------------------------------------------------------------------------------------------------------------------
#    Call Community Model
#--------------------------------------------------------------------------------------------------------------------------

In [32]:
filename = 'gam iconclass sentiment'

In [33]:
# Perspective (user attributes, artworks similarity features, emotion similarity on plutchik emotions similar artworks)
with open('perspectives/' + filename + '.json', 'r', encoding='utf8') as f:
    perspective = json.load(f)[0]
perspective

{'id': 'gam iconclass sentiment',
 'name': 'gam iconclass sentiment',
 'algorithm': {'name': 'agglomerative', 'params': []},
 'similarity_functions': [{'sim_function': {'name': 'IconClassSimilarityDAO',
    'params': [],
    'on_attribute': {'att_name': 'Iconclass_subjects_curators',
     'att_type': 'String'},
    'weight': 0.8}}],
 'user_attributes': [{'att_name': 'RelationshipWithArt',
   'att_type': 'String'},
  {'att_name': 'RelationshipWithMuseum', 'att_type': 'String'}],
 'interaction_similarity_functions': [{'sim_function': {'name': 'PlutchikEmotionSimilarityDAO',
    'params': [],
    'on_attribute': {'att_name': 'emotions', 'att_type': 'dict'},
    'interaction_object': {'att_name': 'IdArtefact',
     'att_type': 'String',
     'mode': 'similar'}}}]}

In [34]:
from communityModel.communityModel import CommunityModel
from communityModel.artworkModel import ArtworkModel
from dao.dao_json import DAO_json

In [35]:
# Call Community Model
communityModel = CommunityModel(perspective)

In [36]:
communityModel.start()

file doesnt exist
Sz5Wx2XD
Sz5Wx2XD
{'sim_function': {'name': 'PlutchikEmotionSimilarityDAO', 'params': [], 'on_attribute': {'att_name': 'emotions', 'att_type': 'dict'}, 'interaction_object': {'att_name': 'IdArtefact', 'att_type': 'String', 'mode': 'similar'}}}
objectA: 35245
IOB: [35245]


IO_distanceIndex: [35246, 35211, 35250, 35381, 35456, 35499, 35362, 35227, 35323, 35374, 35237, 35210, 35230, 35288, 39182, 35217, 39648, 39384, 35364, 39347, 35433, 35236, 41209, 35308, 39425, 35279, 35445, 39427, 39426, 39200, 35330, 39352, 39364, 35310, 35412, 35287, 35229, 35213, 35465, 35222, 35321, 35225, 35360, 35209, 39416, 35459, 39138, 35232, 35233, 39175, 35249, 35567, 35208, 35224, 35245, 35212]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


objectA index: 54
distanceMatrix_IOB_indexes: [54]
distanceMatrix_IOB_values: [1.]
minimumDistance index: 0
minimumDistance value: 1.0
most

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


objectA index: 20
distanceMatrix_IOB_indexes: [26]
distanceMatrix_IOB_values: [1.]
minimumDistance index: 0
minimumDistance value: 1.0
most similar IO: 35445




interactionsA: [{}]
interactionsB: [{'Serenity': 1}]
objectIndexA: 0
len IOA: 1
IOA: [35433]
yjlouq5U
interactionFeatureA: {}
interactionFeatureB: {'Serenity': 1}
dominantA: 
dominantB: serenity
distance: 1.0
distanceTotal: 0
dominantInteractionAttributeList: ['', '', '', '', '', '', '']
yjlouq5U
q2BDj1os
{'sim_function': {'name': 'PlutchikEmotionSimilarityDAO', 'params': [], 'on_attribute': {'att_name': 'emotions', 'att_type': 'dict'}, 'interaction_object': {'att_name': 'IdArtefact', 'att_type': 'String', 'mode': 'similar'}}}
objectA: 35433
IOB: [39138]


IO_distanceIndex: [35246, 35211, 35250, 35381, 35456, 35499, 35362, 35227, 35323, 35374, 35237, 35210, 35230, 35288, 

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


objectA index: 44
distanceMatrix_IOB_indexes: [6]
distanceMatrix_IOB_values: [1.]
minimumDistance index: 0
minimumDistance value: 1.0
most similar IO: 35362




interactionsA: [{'Serenity': 0.5474502, 'Joy': 1}, {'Anticipation': 1.90175444, 'Fear': 1.95738137}, {'Joy': 1}, {'Joy': 0.66874564, 'Trust': 1}, {'Sadness': 1, 'Serenity': 1}, {'Serenity': 1}, {'Serenity': 1}, {'Serenity': 2.98774594, 'Joy': 1}, {'Fear': 1, 'Interest': 1}, {}, {'Disgust': 1}]
interactionsB: [{}]
objectIndexA: 0
len IOA: 11
IOA: [39416, 35433, 39648, 39175, 35380, 39347, 39347, 35227, 39182, 35222, 35567]
RQ4a2nIG
interactionFeatureA: {'Serenity': 0.5474502, 'Joy': 1}
interactionFeatureB: {}
dominantA: joy
dominantB: 
distance: 1.0
distanceTotal: 0
objectA: 35433
IOB: [35362]


IO_distanceIndex: [35246, 35211, 35250, 35381, 35456, 35499, 35362, 35227, 3532

[[1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   0.   0.64 1.   1.   0.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   0.64 0.64 1.   1.   0.64 1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   0.   0.64 1.   1.   0.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  

TypeError: ExplainedCommunitiesDetection.interaction_is_explainable() takes from 2 to 3 positional arguments but 4 were given

In [ ]:
communityModel.similarityMeasure.data

In [ ]:
communityModel.clustering(percentageExplainability = 0.5, exportFile = "clustering/GAM.json")

In [ ]:
communityModel.computeDistanceMatrix()

In [ ]:
communityModel.initializeSimilarityMeasure()

In [ ]:
from communityModel.communityModel import CommunityModel


In [ ]:
communityModel.clustering(percentageExplainability = 0.5, exportFile = "clustering/GAM.json")